modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/wachipayox/WBackpacks/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/wachipayox/WBackpacks"
authors="Wachipayoxx"
description='''
Windowed backpacks for Minecraft. Open backpack storage directly on top of normal inventory and container screens, keep several movable windows open at once, and arrange them like a tiny desktop without leaving the inventory you are already using.
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
